### ISSUE TITLE
Move to cats checklist

### ISSUE THREAD

**Issue by julien-truffaut** [julien-truffaut/Monocle#677]
- [x] release 1.6.0 with scalaz
- [x] support Scala 2.13 and cats 2.0 on cats branch
- [x] re-enable commented tests on cats branch
- [x] create scalaz branch from master
- [x] replace master by cats branch
- [x] check no missing commits https://github.com/julien-truffaut/Monocle/compare/branch1..branch2
- [x] remove type alias like `import scala.{Left => -\/}`
- [x] release 2.0.0-RC1 with cats

**Comment by cquiroz** [comment]
On the master there are many type aliases, which I think are to ease sharing code across scalaz/cats. Do you think those should removed?
e.g.

`import scala.{Left => -\/}`
`import scala.{List => IList}`

**Comment by julien-truffaut** [comment]
Yes we should remove them after master uses the cats branch.

**Comment by cquiroz** [comment]
Another task maybe, Do a last `monocle-cats-1.5/1.6` release with cats 1.6.1 and the latest changes?

**Comment by Daenyth** [comment]
Is there any blocker to releasing a current 1.6.0-cats build on cats 2.x for 2.13 support?

**Comment by julien-truffaut** [comment]
cats 2.0-RC1 should be release today or tomorrow. I will cut Monocle 2.0-RC1 after that

**Comment by xuwei-k** [comment]
@julien-truffaut please configure protect setting `scalaz` branch 🙏  https://help.github.com/en/articles/about-protected-branches

**Comment by julien-truffaut** [comment]
@xuwei-k done, do you think I should add other protection like PR only? Btw, I thought you had admin right if it is not the case, would you take them?
